name: Daily Trend Pipeline

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install prophet
      - name: Set up secrets
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          ALERT_EMAIL_TO: ${{ secrets.ALERT_EMAIL_TO }}
          ALERT_EMAIL_FROM: ${{ secrets.ALERT_EMAIL_FROM }}
          ALERT_SMTP_SERVER: ${{ secrets.ALERT_SMTP_SERVER }}
          ALERT_SMTP_PORT: ${{ secrets.ALERT_SMTP_PORT }}
          ALERT_SMTP_USER: ${{ secrets.ALERT_SMTP_USER }}
          ALERT_SMTP_PASS: ${{ secrets.ALERT_SMTP_PASS }}
        run: |
          echo "Secrets loaded."
      - name: Run data fetch
        run: python run_fetch.py
      - name: Run trend analysis
        run: python trend_analysis/run_trends.py
      - name: Run insights engine
        run: python insights_engine/run_insights.py 